name: Docker Image GHCR

on:
  create:
    tags:
    - '*'

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      env:
        GITHUB_USERNAME: ${{ secrets.G_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        DOCKER_BUILDKIT: 1
      run: |
        docker build . --file Dockerfile -t ghcr.io/${{ github.repository_owner }}/necessities:${{ steps.get_version.outputs.VERSION }}
        docker tag ghcr.io/${{ github.repository_owner }}/necessities:${{ steps.get_version.outputs.VERSION }} ghcr.io/${{ github.repository_owner }}/necessities:latest
        docker push ghcr.io/${{ github.repository_owner }}/necessities:${{ steps.get_version.outputs.VERSION }}
        docker push ghcr.io/${{ github.repository_owner }}/necessities:latest
